### ISSUE TITLE
Documentation: difference between 🆖 and ❌

### ISSUE THREAD

**Issue by nicolasgasco** [greg-gav/ft_containers_tester#1]
Hi! I think it would be worth exaplaining in your README what the difference is between 🆖  and ❌. There is no log in case of successful compilation, so I'm a bit confused on how I should debug this.

In my case, I'm getting 🆖 on the empty constructor, which should be straight-forward enough to get a pass

<img width="749" alt="Screenshot 2022-12-11 at 09 57 28" src="https://user-images.githubusercontent.com/73175085/206895522-2edcd572-27b1-4bfc-a240-bd1ae80e94c5.png">

I see in your screengrab that you're also getting 🆖 for the default constructor, so maybe it only means that there's no output to check? In which case, I found "no good" to be confusing

**Comment by greg-gav** [comment]
It's not very good design on my part and you are right - in case there is no output to check it is expected behaviour to get an NG which is "No Grade".
It also appears in case of there is no output to check due to unexpected exit code (segfault etc.) or timeout - in this case its a sign that cause of NG should be investigated further.
This can be clarified in the readme or error handling can be reworked to give clearer explanations of what happened.

**Comment by nicolasgasco** [comment]
Oh, I see. I checked the meaning of that emoji and apparently it means "no good", hence the confusion. Maybe as a simple fix it can be replaced by something else, e.g. `-`.
But you're right, I'm getting some NGs that are caused by other errors. I think in those cases `CODE: -6` or `TIMEOUT` are enough indication that something is not working. I don't see reworking the error handling as necessary.

**Comment by greg-gav** [comment]
Updated readme to clarify this.
