### ISSUE TITLE
Bug: `std::equal` not compiling when using own re-implementation of `iterator`

### ISSUE THREAD

**Issue by nicolasgasco** [greg-gav/ft_containers_tester#2]
Hi! I noticed an issue with your test suite.
It uses `std::equal`, so it doesn't work if you use your own implementation of the `iterator` class.

It's still a bit fuzzy to me, but I noticed you can do this project by declaring the iterator either:
- using a pointer and `iterator_traits`, e.g. `typedef typename ft::iterator_traits<ft::iterator<value_type> >::pointer iterator`
- directly your `iterator` class, e.g. `typedef typename ft::iterator<value_type> iterator`

When choosing the second formula, your tests fail because of `std::equal`. The issue is fixed by replacing `ft::equal` (which is part of the subject requirements anyway).

I think we're supposed to use our own implementation of `iterator` and not just a pointer because other testers check that and don't compile if you use a simple pointer.

If you deem it necessary, I can prepare a pull request.

**Comment by greg-gav** [comment]
From what I've seen its not a problem to use pointer approach and also compatibility with `std::equal` for your implementation is a good thing rather than something bad.
I don't think that changing this is necessary, unless there is some evidence that pointer approach is plain wrong and shouldn't be used.

**Comment by greg-gav** [comment]
From what I've seen its not a problem to use pointer approach and also compatibility with `std::equal` for your implementation is a good thing rather than something bad.
I don't think that changing this is necessary, unless there is some evidence that pointer approach is plain wrong and shouldn't be used.
Also I don't think that using an `iterator` class directly necessarily breaks `std::equal`, I think it could be compatible depending on the implementation.

**Comment by nicolasgasco** [comment]
I get your point. For the sake of reviewing this project, I would accept both approaches since there's no explicit mention of re-implementing the `iterator` class in the subject.

Some testers consider it sort of mandatory. [In this open issue](https://github.com/divinepet/ft_containers-unit-test/issues/5), for example, you can see that a case is mentioned where pointers don't compile: `++vect.begin()`.

I don't think that not being able to compile that statement makes or breaks the project, but it's also true that `ft::equal` is required in the subject, so it wouldn't feel unnatural to use it in a tester.

I created a fork where I replace `std::equal` with `ft::equal` if you want to have a look: https://github.com/nicolasgasco/ft_containers_tester

In the meantime, I will see if it's possible to overload `std::equal` to accept our re-implemented classes. That would be indeed the safest approach.

Thank you for your reaction!

**Comment by greg-gav** [comment]
Fork looks good, and it is a good workaround for this issue.
Thanks for your input and providing more info on this!
